import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "StreamVibe - Watch Movies & TV Shows Online | Unlimited Streaming",
  description: "Stream thousands of movies, TV shows, and documentaries instantly on StreamVibe.Watch the latest blockbusters, classic films, and binge-worthy series on any device. Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Header/>
        <Footer/>
          <main className="min-h-svh">{children}</main>     
      </body>
    </html>
  );
}
